baseURL = "/"
languageCode = "en-us"
title = "Neonailol"
theme = "academic"
pygmentsCodefences = true
pygmentsStyle = "solarized"
enableGitInfo = true

[outputs]
    home = [ "HTML", "CSS", "RSS", "JSON" ]
    section = [ "HTML", "RSS" ]

[params]
    color_theme = "default"
    font = "default"
    name = "Valeriy Zhirnov"
    role = "Software Developer"
    avatar = "portrait.jpg"
    telegram = "neonailol"
    twitter = "neonailol"
    date_format = "2006-01-02"
    time_format = "00:00"
    highlight = true
    highlight_languages = ["kotlin"]
    highlight_style = "monokai"

[[params.social]]
    icon = "github"
    icon_pack = "fab"
    link = "//github.com/neonailol"

[[params.social]]
    icon = "telegram"
    icon_pack = "fab"
    link = "//t.me/neonailol"

[[params.social]]
    icon = "twitter"
    icon_pack = "fab"
    link = "//twitter.com/neonailol"

[params.menus]
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Notes"
  url = "notes"
  weight = 1

